# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)/azdemo'
    gradleWrapperFile: '$(Build.SourcesDirectory)/azdemo/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/azdemo/build/libs' 
    Contents: '*-SNAPSHOT.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true

- publish: '$(Build.ArtifactStagingDirectory)' 
  artifact: WebApp

# - task: AzureWebApp@1
#   # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   inputs:
#     azureSubscription: 'azure-azdemo'
#     appName: 'azdemo001'

- script: 'find $(System.ArtifactsDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure-azdemo'
    appType: 'webAppLinux'
    WebAppName: 'azdemo001'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*-SNAPSHOT.jar'
    RuntimeStack: 'JAVA|17-java17'
    StartupCommand: 'java -jar /home/site/wwwroot/azdemo-0.0.1-SNAPSHOT.jar --server.port=80'
    